### ISSUE TITLE
Crash on Galsxy S4. 

### ISSUE THREAD

**Issue by Tooto** [googlesamples/android-MediaRecorder#2]
By click on "Capture" button app Crashes 

08-26 14:33:10.771  23481-23822/com.example.android.mediarecorder E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.example.android.mediarecorder, PID: 23481
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException: start failed.
            at android.media.MediaRecorder.start(Native Method)
            at com.example.android.mediarecorder.MainActivity$MediaPrepareTask.doInBackground(MainActivity.java:208)
            at com.example.android.mediarecorder.MainActivity$MediaPrepareTask.doInBackground(MainActivity.java:200)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-26 14:33:11.651  23481-23506/com.example.android.mediarecorder E/OpenGLRenderer﹕ SFEffectCache:clear(), mSize = 0

**Comment by maricatovictor** [comment]
It also crashes on Galaxy S5 Mini.

**Comment by alfdev** [comment]
Hi guys,
has someone solved the issue?

thanks

**Comment by yaraki** [comment]
I don't have Galaxy S4 or S5, so I cannot debug this issue. Can anybody provide a pull request?

**Comment by makokev** [comment]
Hi,
it crash also on Nexus 4 and 6.
Could you tell me on what smartphone doesn't it crash?
Thank you so much.
Kev

**Comment by dturner** [comment]
Closing as stale. Please reopen if you're still having this issue.
